/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { R_TokenContract } from "./R_TokenContract";
export type { TokenStakingContract } from "./TokenStakingContract";
